version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: user123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: back-app
    container_name: back-app
    build:
      context: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: user123
      DB_DATABASE: db123
